#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

python manage.py makemigrations
python manage.py migrate


#python manage.py loaddata Habit_fixture.json

python manage.py telega &

python manage.py add_user

python manage.py runserver 0.0.0.0:8000